### ISSUE TITLE
Code page guidelines

### ISSUE THREAD

**Issue by IamShubhamGupto** [m2lines/m2lines.github.io#53]
## Proposal

- Move to a `yml` file based approach where each repository consists of metadata that the authors want to show off on the m2lines website. The idea is the website will only be responsible for hosting the content while the authors of each repository are responsible for proving the content
- The current idea is to automatically parse metadata from said `yml` file and update the `code` page accordingly. The idea is to currently support repositories within the M2Lines organization and then plan on how to branch out to general repositories.

## ToDos
- [ ] Get a list of repositories that should be hosted on the code page
- [ ] Create a template on how to host repositories 
- [ ] Create a dummy repository to test parsing and building automatic content
- [ ] Create a GitHub action to run yml parsing at regular interval
- [ ] Add `yml` file to all M2Lines repositories
